spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/search-engine
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

scheduled:
  fixed:
    delay:
      millis: 86400000
